03 mongodb
Oleksandr1301/nodejs-homework-template pull request #2
Opened 2023-07-15 19:21 UTC by Oleksandr1301

Доброго вечора! Перевірте будь ласка hw3

2023-07-16 13:42 UTC, KhYulian commented on controllers/index.js
> +const getContactById = async contactId => Contact.findById(contactId)
```suggestion
const getContactById = async contactId => Contact.findById(contactId)
```

потрібно додати перевірку на те чи знайдено контакт

2023-07-16 13:42 UTC, KhYulian commented on controllers/index.js
> +const getContactById = async contactId => Contact.findById(contactId)
```suggestion
const getContactById = async contactId => await Contact.findById(contactId)
```

2023-07-16 13:42 UTC, KhYulian commented on controllers/index.js
> +const getAllContacts = async () => Contact.find()
```suggestion
const getAllContacts = async () => await Contact.find()
```

2023-07-16 13:44 UTC, KhYulian commented on controllers/contacts.js
цей файл має називатись Contact.js і бути розміщеним в кореневій папці у папці models

2023-07-16 13:44 UTC, KhYulian commented on models/contacts.js
цей файл має бути в кореневій папці в папці controllers

2023-07-16 13:44 UTC, KhYulian commented on models/contacts.js
> +	console.log('contacts: ', contacts)
```suggestion

```
видаліть зайві логи

2023-07-16 13:45 UTC, KhYulian commented on models/contacts.js
файл назвіть contactsControllers

2023-07-16 13:45 UTC, KhYulian commented on controllers/index.js
> +const getAllContacts = async () => Contact.find()
все, що пов'язано із запитами в бд - це асинхронні функції і потрібно використовувати await

2023-07-16 13:46 UTC, KhYulian commented on controllers/index.js
цей файл назвіть contactsServices і помістіть його в папку services, яка має бути в кореневій папці

2023-07-16 13:46 UTC, KhYulian requested changes
Потрібне доопрацювання

2023-07-17 16:52 UTC, Oleksandr1301 commented
Доброго вечора! Доопрацював hw3

2023-07-17 20:05 UTC, merged